### ISSUE TITLE
Contributing to the Python Analyzer

### ISSUE THREAD

**Issue by omer-g** [exercism/python-analyzer#1]
Hello, I'd be happy to get involved with the development of the Python Analyzer. Let me know if there is somewhere I could help. Thanks :)

**Comment by iHiD** [comment]
@omer-g Thanks! So the only problem we have a little bit is that I'm not sure who's the "responsible adult" for this repo atm.

@TreyAguirre Are you planning on continuing to maintain this beyond your university project, or are you planning on handing over responsibility to the Python maintainers when that's done? Or a bit of both? :)

@exercism/python - Are you planning on actively moving this forward in the future?

**Comment by TreyAguirre** [comment]
@iHiD I'd love to continue maintaining the Python analyzer beyond my CS 5152 course!

**Comment by cmccandless** [comment]
Responding for @exercism/python.

I am available for code reviews, but I don't have the bandwidth to actively work development for this myself. As it is, our WIP test generator is at a stand-still because neither I nor the contributor who started work on it has the time to finish it.
