### ISSUE TITLE
Pylint is complaining about invalid/useless flags.

### ISSUE THREAD

**Issue by IsaacG** [exercism/python-analyzer#56]
For Ellen's Alien Game, Pylint is complaining about:

```
Line 1 [E0015 unrecognized-option] : ["Unrecognized option found: no-space-check"] was reported by Pylint.
Line 1 [W0012 unknown-option-value] : ["Unknown option value for '--disable'", "expected a valid pylint message and got 'misplaced-comparison-constant'"] was reported by Pylint.
Line 1 [W0012 unknown-option-value] : ["Unknown option value for '--disable'", "expected a valid pylint message and got 'relative-import'"] was reported by Pylint.
Line 1 [R0022 useless-option-value] : ["Useless option value for '--disable'", "'input-builtin' was removed from pylint", "see https://github.com/PyCQA/pylint/pull/4942."] was reported by Pylint.
Line 1 [R0022 useless-option-value] : ["Useless option value for '--disable'", "'no-absolute-import' was removed from pylint", "see https://github.com/PyCQA/pylint/pull/4942."] was reported by Pylint.
Line 1 [R0022 useless-option-value] : ["Useless option value for '--disable'", "'raising-string' was removed from pylint", "see https://github.com/PyCQA/pylint/pull/4942."] was reported by Pylint.
Line 1 [R0022 useless-option-value] : ["Useless option value for '--disable'", "'round-builtin' was removed from pylint", "see https://github.com/PyCQA/pylint/pull/4942."] was reported by Pylint.
```

I'm not sure why or what but it would seem that the analyzer may need updates in light of recent updates to Pylint and/or Exercism's Python version.

**Comment by BethanyG** [comment]
Commenting here, so there is a record.  For all exercises except `two-fer` and `Ellen's Alien Game`, the analyzer uses a central `.pylintrc` file located in [`lib/common`](https://github.com/exercism/python-analyzer/tree/main/lib/common).  

However, `Ellen's Alien Game` uses a `.pylintrc` file located in [`/lib/ellens-alien-game`](https://github.com/exercism/python-analyzer/tree/main/lib/ellens-alien-game) that overrides the common file.

`Two-Fer` uses both the common `.pylintrc` file _as well as_ custom hand-built analyzer rules found in [`lib/two-fer`](https://github.com/exercism/python-analyzer/blob/main/lib/two-fer/)

In the upgrade to Python `3.1.6`, the `.pylintrc` file under `/lib/ellens-alien-game/` was missed, and it included deprecated rules and Python methods that were pissing off pylint.  Hence the errors output for analysis feedback.

**Comment by BethanyG** [comment]
As a note:  we need to review the `.pylintrc` file located in the main repo for students to download for local work.  I suspect it's not as updated as we'd like it to be.  I don't remember editing it in the `3.10.6` upgrade...  😱
