### ISSUE TITLE
Move image away from alpine base

### ISSUE THREAD

**Issue by cmccandless** [exercism/python-analyzer#8]
See the following for more information:
- [Alpine makes Python Docker builds 50× slower, and images 2× larger](https://pythonspeed.com/articles/alpine-docker-python/)
- [The best Docker base image for your Python application (January 2020)](https://pythonspeed.com/articles/base-image-python-docker-images/)

**Comment by pyropy** [comment]
@cmccandless Hi, can I take a look at this issue? I would like to expirement for a bit and see for myself what would be a good solution. 

I also use Docker python images for my development at work so this knowledge would benefit me at work also :D

**Comment by cmccandless** [comment]
By all means, have at it!

**Comment by cmccandless** [comment]
Closed by #10
