### ISSUE TITLE
"Reverse String" exercise auto-grading

### ISSUE THREAD

**Issue by lancelote** [exercism/python-analyzer#9]
Hi, "Reverse String" exercise has an "ideal" solution

```python
def reverse(text):
    return text[::-1]
```

... which can be auto-accepted I think. People submit it quite often for review and I am already tired accepting it.

Is it something worth looking into and contributing? Is the project still active and will it be used in v3?

**Comment by cmccandless** [comment]
@lancelote Hello!

Apologies for the delayed response, this repo fell between the tracks a bit for the last couple months. Yes it will still be in use in v3, but "ideal, auto-accepted" solutions will be detected by something new we're using along with the analyzer call "Representers". If you'd like to learn more, take a look at the v3 plan [here](https://github.com/exercism/v3/issues/690).

**Comment by BethanyG** [comment]
Flagging this as `wontfix` because the way we are reviewing and mentoring exercises is changing for V3.  That being said, the above solution is indeed an ideal one that will be noted as such for automated analysis.  😄
